### ISSUE TITLE
Dining common menus 

### ISSUE THREAD

**Issue by emsgau** [whyyao/GoGauchoAndroidFeedbacks#2]
Hi,

After the latest update, the dining commons menus aren't showing up. 

But I like how the map feature has been fixed. The added weekly schedule feature is awesome too! Great work with the app.

**Comment by whyyao** [comment]
Hi there, I am glad that you liked the weekly schedule!
The issue should be fixed for dining commons, do they show up now?

Thanks for the report!

**Comment by emsgau** [comment]
Hi!

It was working for the past few days. I checked right now and it gave me a
timeout error, I attached a picture.

Thanks!
